import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar flex items-center">
          <Link href="/" className="logo">
            <h1>Appleforum</h1>
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
        </div>
        <main>{children}</main>
      </body>
    </html>
  );
}
