import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import LoginButton from '@/components/LoginButton';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar flex items-center">
          <Link href="/" className="logo">
            <h1>Appleforum</h1>
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          {session && (
            <>
              <section className="profile_box flex items-center gap-10">
                <img
                  className="profile_img"
                  src={session.user.image}
                  alt={session.user.name}
                />
                <p>{session.user.email}</p>
              </section>
            </>
          )}
          <LoginButton user={session?.user} />
        </div>

        <main>{children}</main>
      </body>
    </html>
  );
}
